CREATE TABLE Dim_Tag (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE Dim_projeto (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE Dim_status (
    id BIGSERIAL PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL
);

CREATE TABLE Fato_Progresso_user_stories (
    id BIGSERIAL PRIMARY KEY,
    id_tag BIGINT,
    id_projeto BIGINT,
    id_status BIGINT,
    quantidade_user_stories BIGINT,
    FOREIGN KEY (id_tag) REFERENCES Dim_Tag(id),
    FOREIGN KEY (id_projeto) REFERENCES Dim_projeto(id),
    FOREIGN KEY (id_status) REFERENCES Dim_status(id)
);
CREATE TABLE FATO_STATUS_USER_STORY(
	ID BIGSERIAL PRIMARY KEY,
	ID_STATUS BIGSERIAL, 
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORY INT,
	CONSTRAINT FK_FT_ST_US
	FOREIGN KEY (ID_STATUS)
	REFERENCES DIM_STATUS (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_PROJETO_US
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE
);

CREATE TABLE FATO_TAG_USER_STORY(
	ID BIGSERIAL PRIMARY KEY,
	ID_TAG BIGSERIAL, 
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORY INT,
	CONSTRAINT FK_FT_TAG_US
	FOREIGN KEY (ID_TAG)
	REFERENCES DIM_TAG (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_PROJETO_US
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE
);

CREATE TABLE DIM_USER_STORY(
	ID BIGSERIAL PRIMARY KEY, 
	ASSUNTO VARCHAR(255),
	CRIADO_EM TIMESTAMPTZ,
	FINALIZADO_EM TIMESTAMPTZ,
	BLOQUEADO BOOLEAN,
	ENCERRADO BOOLEAN,
	DATA_LIMITE TIMESTAMPTZ
);

CREATE TABLE DIM_USUARIO (
	ID BIGSERIAL PRIMARY KEY, 
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	SENHA VARCHAR(255),
	ROLE VARCHAR(20)
);

CREATE TABLE DIM_PERIODO (
	ID BIGSERIAL PRIMARY KEY,
	NOME VARCHAR(100)
);

CREATE TABLE FATO_USER_STORY_TEMPORAIS (
	ID BIGSERIAL PRIMARY KEY, 
	ID_USUARIO BIGSERIAL, 
	ID_PERIODO BIGSERIAL,
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORIES_FINALIZADAS INT,
	QUANTIDADE_USER_STORIES_CRIADAS INT,
	CONSTRAINT FK_FT_PROJETO_US_TEMPORAIS
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE,
	CONSTRAINT FK_FT_US_PERIODO_TEMPORAIS
	FOREIGN KEY (ID_PERIODO)
	REFERENCES DIM_PERIODO (ID) ON DELETE CASCADE	
);

CREATE TABLE FATO_EFICIENCIA_USER_STORY (
	ID BIGSERIAL PRIMARY KEY, 
	ID_USUARIO BIGSERIAL, 
	ID_USER_STORY BIGSERIAL,
	ID_PROJETO BIGSERIAL,
	TEMPO_MEDIO DOUBLE PRECISION,
	CONSTRAINT FK_FT_PROJETO_US_EFICIENCIA
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE,
	CONSTRAINT FK_FT_USUARIO_US_EFICIENCIA
	FOREIGN KEY (ID_USUARIO)
	REFERENCES DIM_USUARIO (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_USER_STORY_US_EFICIENCIA
	FOREIGN KEY (ID_USER_STORY)
	REFERENCES DIM_USER_STORY (ID) ON DELETE CASCADE
);