DROP TABLE IF EXISTS Dim_Tag CASCADE;

CREATE TABLE DIM_TAG (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS Dim_Projeto CASCADE;
CREATE TABLE DIM_PROJETO (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS Dim_status CASCADE;
CREATE TABLE DIM_STATUS (
    id BIGSERIAL PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS FATO_TAG_USER_STORY CASCADE;

CREATE TABLE FATO_TAG_USER_STORY (
    id BIGSERIAL PRIMARY KEY,
    id_tag BIGINT,
    id_projeto BIGINT,
    quantidade_user_stories BIGINT,
    FOREIGN KEY (id_tag) REFERENCES Dim_Tag(id),
    FOREIGN KEY (id_projeto) REFERENCES Dim_projeto(id)
);

DROP TABLE IF EXISTS FATO_STATUS_USER_STORY CASCADE;
CREATE TABLE FATO_STATUS_USER_STORY(
	ID BIGSERIAL PRIMARY KEY,
	ID_STATUS BIGSERIAL, 
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORY INT,
	CONSTRAINT FK_FT_ST_US
	FOREIGN KEY (ID_STATUS)
	REFERENCES DIM_STATUS (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_PROJETO_US
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE
);


DROP TABLE IF EXISTS FATO_TAG_USER_STORY CASCADE;

CREATE TABLE FATO_TAG_USER_STORY(
	ID BIGSERIAL PRIMARY KEY,
	ID_TAG BIGSERIAL, 
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORY INT,
	CONSTRAINT FK_FT_TAG_US
	FOREIGN KEY (ID_TAG)
	REFERENCES DIM_TAG (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_PROJETO_US
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS DIM_USER_STORY CASCADE;
CREATE TABLE DIM_USER_STORY(
	ID BIGSERIAL PRIMARY KEY, 
	ASSUNTO VARCHAR(255),
	CRIADO_EM TIMESTAMPTZ,
	FINALIZADO_EM TIMESTAMPTZ,
	BLOQUEADO BOOLEAN,
	ENCERRADO BOOLEAN,
	DATA_LIMITE TIMESTAMPTZ
);

DROP TABLE IF EXISTS DIM_USUARIO CASCADE;

CREATE TABLE DIM_USUARIO (
	ID BIGSERIAL PRIMARY KEY, 
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	SENHA VARCHAR(255),
	ROLE VARCHAR(20)
);

DROP TABLE IF EXISTS DIM_PERIODO CASCADE;

CREATE TABLE DIM_PERIODO (
	ID BIGSERIAL PRIMARY KEY,
	NOME VARCHAR(100)
);

DROP TABLE IF EXISTS FATO_USER_STORY_TEMPORAIS CASCADE;

CREATE TABLE FATO_USER_STORY_TEMPORAIS (
	ID BIGSERIAL PRIMARY KEY, 
	ID_USUARIO BIGSERIAL, 
	ID_PERIODO BIGSERIAL,
	ID_PROJETO BIGSERIAL,
	QUANTIDADE_USER_STORIES_FINALIZADAS INT,
	QUANTIDADE_USER_STORIES_CRIADAS INT,
	CONSTRAINT FK_FT_PROJETO_US_TEMPORAIS
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE,
	CONSTRAINT FK_FT_US_PERIODO_TEMPORAIS
	FOREIGN KEY (ID_PERIODO)
	REFERENCES DIM_PERIODO (ID) ON DELETE CASCADE	
);

DROP TABLE IF EXISTS FATO_EFICIENCIA_USER_STORY CASCADE;

CREATE TABLE FATO_EFICIENCIA_USER_STORY (
	ID BIGSERIAL PRIMARY KEY, 
	ID_USUARIO BIGSERIAL, 
	ID_USER_STORY BIGSERIAL,
	ID_PROJETO BIGSERIAL,
	TEMPO_MEDIO DOUBLE PRECISION,
	CONSTRAINT FK_FT_PROJETO_US_EFICIENCIA
	FOREIGN KEY (ID_PROJETO)
	REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE,
	CONSTRAINT FK_FT_USUARIO_US_EFICIENCIA
	FOREIGN KEY (ID_USUARIO)
	REFERENCES DIM_USUARIO (ID) ON DELETE CASCADE,	
	CONSTRAINT FK_FT_USER_STORY_US_EFICIENCIA
	FOREIGN KEY (ID_USER_STORY)
	REFERENCES DIM_USER_STORY (ID) ON DELETE CASCADE
);
-- V2.0

ALTER TABLE DIM_USER_STORY 
ADD COLUMN ID_STATUS BIGINT NOT NULL,
ADD CONSTRAINT FK_DUS_STATUS FOREIGN KEY (ID_STATUS) REFERENCES DIM_STATUS (ID) ON DELETE CASCADE;

ALTER TABLE DIM_USER_STORY 
ADD COLUMN ID_TAIGA BIGINT NOT NULL,
ADD COLUMN ID_USUARIO BIGINT NOT NULL,
ADD CONSTRAINT FK_DUS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES DIM_USUARIO (ID) ON DELETE CASCADE,
ADD COLUMN ID_PROJETO BIGINT NOT NULL,
ADD CONSTRAINT FK_DUS_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES DIM_PROJETO (ID) ON DELETE CASCADE;

ALTER TABLE FATO_EFICIENCIA_USER_STORY 
DROP CONSTRAINT IF EXISTS FK_FT_PROJETO_US_TEMPORAIS,
DROP COLUMN IF EXISTS ID_PROJETO;

DROP TABLE IF EXISTS RELACIONAMENTO_TAG_USER_STORY;
CREATE TABLE RELACIONAMENTO_TAG_USER_STORY (
    ID_STATUS BIGINT,
    ID_USER_STORY BIGINT,
    CONSTRAINT PK_RELACIONAMENTO_TAG_USER_STORY PRIMARY KEY (ID_STATUS, ID_USER_STORY),
    CONSTRAINT FK_RELACIONAMENTO_TU_STATUS FOREIGN KEY (ID_STATUS) REFERENCES DIM_STATUS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_RELACIONAMENTO_TU_USER_STORY FOREIGN KEY (ID_USER_STORY) REFERENCES DIM_USER_STORY(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS RELACIONAMENTO_PROJETO_USUARIO;
CREATE TABLE RELACIONAMENTO_PROJETO_USUARIO (
    ID_USUARIO BIGINT,
    ID_PROJETO BIGINT,
    CONSTRAINT PK_RELACIONAMENTO_PU PRIMARY KEY (ID_USUARIO, ID_PROJETO),
    CONSTRAINT FK_RELACIONAMENTO_PU_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES DIM_USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_RELACIONAMENTO_PU_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES DIM_PROJETO(ID) ON DELETE CASCADE
);

-- ALTERANDO CHAVES ESTRANGEIRAS PARA BIGINT
ALTER TABLE FATO_TAG_USER_STORY 
ALTER COLUMN ID_TAG SET DATA TYPE BIGINT,
ALTER COLUMN ID_PROJETO SET DATA TYPE BIGINT;

ALTER TABLE FATO_STATUS_USER_STORY 
ALTER COLUMN ID_STATUS SET DATA TYPE BIGINT,
ALTER COLUMN ID_PROJETO SET DATA TYPE BIGINT;

ALTER TABLE FATO_TAG_USER_STORY 
ALTER COLUMN ID_TAG SET DATA TYPE BIGINT,
ALTER COLUMN ID_PROJETO SET DATA TYPE BIGINT;

ALTER TABLE FATO_USER_STORY_TEMPORAIS 
ALTER COLUMN ID_USUARIO SET DATA TYPE BIGINT,
ALTER COLUMN ID_PERIODO SET DATA TYPE BIGINT,
ALTER COLUMN ID_PROJETO SET DATA TYPE BIGINT;

ALTER TABLE FATO_EFICIENCIA_USER_STORY 
ALTER COLUMN ID_USUARIO SET DATA TYPE BIGINT,
ALTER COLUMN ID_USER_STORY SET DATA TYPE BIGINT;